// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhtyhcldtytxsgiphfhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlodHloY2xkdHl0eHNnaXBoZmhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTg3NDgsImV4cCI6MjA2NTY5NDc0OH0.1iSmqgMV5p-QQ8Noa0N7MIc65DrwkjxInHtwgNdUiDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);